# Generated by Django 4.1.5 on 2023-01-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=120)),
                ('response', models.TextField()),
                ('platform', models.TextField(default='', max_length=32)),
                ('status', models.TextField(default='pending')),
                ('completed', models.BooleanField(default=False)),
                ('post_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
