# Generated by Django 4.1.5 on 2023-01-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='post',
            name='generated_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
