# Generated by Django 4.1.5 on 2023-01-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_completed_remove_post_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
