# Generated by Django 4.1.5 on 2023-01-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.TextField(default='pending'),
        ),
    ]
